# Generated by Django 3.1.2 on 2020-10-24 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('body_text', models.TextField()),
                ('day_rating', models.CharField(choices=[('Terrible', 'Terrible'), ('Bad', 'Bad'), ('Average', 'Average'), ('Good', 'Good'), ('Great', 'Great')], max_length=20)),
                ('audio_message', models.TextField(null=True)),
            ],
            bases=('core.basemodel',),
        ),
    ]
